apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    k8s-app: nginx-status-metrics
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1200"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: minio
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: nginx
  type: LoadBalancer
