# This can be a domain that points to a LAN IP address if you
# are accessing the site from another machine's browser or you
# are installing Tator in a VM.
domain: &domain <Insert static IP or domain>
# Requests for these domains will be redirected to the actual domain.
#redirects:
#  - domain: mysite.duckdns.org
#    # Key filename that will be used in secret for this domain.
#    tlsKeyFile: mysite_key.key
#    # Cert filename that will be used in secret for this domain.
#    tlsCertFile: mysite_cert.crt
#    # Key secret name that will be used in secret for this domain.
#    tlsKeySecretName: mysite-tls-key
#    # Cert secret name that will be used in secret for this domain.
#    tlsCertSecretName: mysite-tls-cert
# Enables debug mode for gunicorn. Do NOT enable this in production.
tatorDebug: true
# Enables javascript minification.
useMinJs: false
# Enable this to turn on "down for maintenance" page.
maintenance: false
# Secret key for django. Feel free to change this.
djangoSecretKey: "9q@$1)+x+zh-3csau(zqhheos2e+ncygac#ol2)1@x2w#kkaer"
postgresHost: "postgis-svc"
# Postgres username. Some make commands expect username django, but otherwise
# it can be changed.
postgresUsername: "django"
# Postgres password. Change this for production.
postgresPassword: "django123"
redisHost: "tator-redis-master"
elasticsearchHost: "elasticsearch-master"
objectStorageHost: "minio-master"
# If you are using the docker registry container for your registry, you can
# leave these, otherwise change user/pass to the credentials for your registry.
dockerUsername: "test"
dockerPassword: "test"
dockerRegistry: "localhost:32000"
systemImageRepo: "localhost:32000"
#podGCStrategy: "OnWorkflowCompletion"
#slackToken: "<Your slack API token>" # Optional, for slack notifications
#slackChannel: "<Your slack channel ID>" # Optional, for slack notifications
# Enable this to require HTTPS. Be sure to set true for production deployments!
requireHttps: false
certCron:
  # Enable this to enable a cron job to automatically update certificates
  # periodically from LetsEncrypt. If this is not provided, the Secret objects
  # tls-cert and tls-key must be created manually.
  enabled: false
maintenanceCron:
  # Enable this to allow maintenance cron jobs to run, such as garbage collection
  # of deleted database objects and database backups.
  enabled: true
migrations:
  # Enable this if database migrations are allowed.
  enabled: true
# List of storage classes for use by workflows. One of these will be randomly
# passed as a workflow parameter to algorithm workflows, and randomly selected
# for transcode workflows.
workflowStorageClasses:
  - microk8s-hostpath
pv:
  hostPath:
    path: "/media/kubernetes_share"
# Can optionally supply seperate pv for static files:
staticPv:
  enabled: false
#   nfsServer: "192.168.1.220"
#   nfsMountOptions:
#     - nfsvers=4
#     - nolock
#   path: "/media/kubernetes_alt"
#
pvc:
  size: 10Ti
hpa:
  nginxMinReplicas: 1
  nginxMaxReplicas: 1
  nginxCpuPercent: 50
  gunicornMinReplicas: 1
  gunicornMaxReplicas: 1
  gunicornCpuPercent: 50
# Transcode resource settings
transcoderMaxRamDiskSize: 2Gi
transcoderCpuLimit: 1000m
transcoderMemoryLimit: 2Gi
# Gunicorn resource settings
gunicornCpuLimit: 4000m
gunicornCpuRequest: 1000m
gunicornMemoryLimit: 4Gi
gunicornMemoryRequest: 1Gi
# NGINX resource settings
nginxCpuLimit: 1000m
nginxCpuRequest: 250m
nginxMemoryLimit: 1Gi
nginxMemoryRequest: 250Mi
metallb:
  # Enable this to provide a load balancer implementation on bare metal.
  enabled: false
postgis:
  # Enable this if you want to use the postgis docker image.
  enabled: true
  persistence:
    size: 10Gi
  hostPath: "/media/kubernetes_share/postgis"
redis:
  # Enable this to install the redis helm chart.
  enabled: true
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
  nodeSelector:
    dbServer: "yes"
  usePassword: false
metrics-server:
  enabled: false
elasticsearch:
  # Enable this to install the elasticsearch helm chart.
  enabled: true
  hostPath: "/media/kubernetes_share/elasticsearch"
  persistence:
    enabled: true
  replicas: 1
  clusterHealthCheckParams: wait_for_status=yellow&timeout=1s
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 30Gi
  nodeSelector: 
    dbServer: "yes"
filebeat:
  enabled: false
kibana:
  enabled: false
minio:
  enabled: true
  accessKey: "AKIAIOSFODNN7EXAMPLE"
  secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  persistence:
    size: "1Ti"
    existingClaim: "main-pv-claim"
    subPath: "objects"
  defaultBucket:
    enabled: true
    name: tator
kube-prometheus-stack:
  enabled: false
prometheus-adapter:
  enabled: false
remoteTranscodes:
  # Typically for dev processing is done on the same machine.
  enabled: false
cognito:
  enabled: false
email:
  enabled: false
anonymousRegistration:
  # Enable to allow anyone to register to use the site.
  enabled: true
  # Enable to require email confirmation for anonymous registration. Automatic email 
  # must be configured.
  emailConfirmation: false
organizations:
  # Autocreate on new user registration.
  autocreate: true
  # Disable to allow POST for staff only.
  allowPost: true

