{{ if .Values.requireHttps }}
{{ if .Values.certCron.enabled }}
{{- $selfsignedSettings := dict "Values" .Values "Release" .Release "Chart" .Chart "name" "make-selfsigned" "app" "cert" "selector" "webServer: \"yes\""  "command" "[bash]" "args" "[\"-c\", \"scripts/cert/selfsigned.sh\"]" "hookWeight" "2" "hook" "pre-install" "domain" .Values.domain }}
{{- if hasKey .Values "tlsCertFile" }}
{{ $_ := set $selfsignedSettings "tlsCertFile" .Values.tlsCertFile }}
{{ end }}
{{- if hasKey .Values "tlsKeyFile" }}
{{ $_ := set $selfsignedSettings "tlsKeyFile" .Values.tlsKeyFile }}
{{ end }}
{{- if hasKey .Values "tlsCertSecretName" }}
{{ $_ := set $selfsignedSettings "tlsCertSecretName" .Values.tlsCertSecretName }}
{{ end }}
{{- if hasKey .Values "tlsKeySecretName" }}
{{ $_ := set $selfsignedSettings "tlsKeySecretName" .Values.tlsKeySecretName }}
{{ end }}
{{include "prejob.template" $selfsignedSettings }}
---
{{- if hasKey .Values "aliases" }}
{{- range .Values.aliases }}
{{- $name := printf "make-selfsigned-%s" .tlsKeySecretName }}
{{- $selfsignedSettings := dict "Values" $.Values "Release" $.Release "Chart" $.Chart "name" $name "app" "cert" "selector" "webServer: \"yes\""  "command" "[bash]" "args" "[\"-c\", \"scripts/cert/selfsigned.sh\"]" "hookWeight" "2" "hook" "pre-install" "domain" .domain "tlsCertFile" .tlsCertFile "tlsKeyFile" .tlsKeyFile "tlsCertSecretName" .tlsCertSecretName "tlsKeySecretName" .tlsKeySecretName }}
{{include "prejob.template" $selfsignedSettings }}
---
{{ end }}
{{ end }}
{{- if hasKey .Values "redirects" }}
{{- range .Values.redirects }}
{{- $name := printf "make-selfsigned-%s" .tlsKeySecretName }}
{{- $selfsignedSettings := dict "Values" $.Values "Release" $.Release "Chart" $.Chart "name" $name "app" "cert" "selector" "webServer: \"yes\""  "command" "[bash]" "args" "[\"-c\", \"scripts/cert/selfsigned.sh\"]" "hookWeight" "2" "hook" "pre-install" "domain" .domain "tlsCertFile" .tlsCertFile "tlsKeyFile" .tlsKeyFile "tlsCertSecretName" .tlsCertSecretName "tlsKeySecretName" .tlsKeySecretName }}
{{include "prejob.template" $selfsignedSettings }}
---
{{ end }}
{{ end }}
{{ end }}
{{ end }}
