kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: main-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.size | default "10Ti" }}
{{- if hasKey .Values.pv "mediaShards" }}
{{- range .Values.pv.mediaShards }}
{{- $settings := dict "Values" $.Values "shard" . }}
{{ include "shard.pvc" $settings }}
{{- end }}
{{- end }}
{{- if hasKey .Values.pv "uploadShards" }}
{{- range .Values.pv.uploadShards }}
{{- $settings := dict "Values" $.Values "shard" . }}
{{ include "shard.pvc" $settings }}
{{- end }}
{{- end }}
{{ if .Values.postgis.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgis-pv-claim
  labels:
    app: postgis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgis.persistence.size }}
{{ end }}
