apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  # Specifies the container runtime interface to use (default: docker)
  # must be one of: docker, kubelet, k8sapi, pns
  containerRuntimeExecutor: pns
  artifactRepository: |
    archiveLogs: true
    s3:
      endpoint: tator-minio:9000
      bucket: tator
      region: us-east-2
      insecure: true
      accessKeySecret:
        name: tator-minio
        key: accesskey
      secretKeySecret:
        name: tator-minio
        key: secretkey
      
