apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  containerRuntimeExecutor: pns
  artifactRepository: |
    archiveLogs: true
    s3:
      endpoint: tator-minio.default.svc.cluster.local:9000
      bucket: tator
      region: us-east-2
      insecure: true
      accessKeySecret:
        name: tator-minio
        key: accesskey
      secretKeySecret:
        name: tator-minio
        key: secretkey
      
